import type { Metadata } from "next";
import {
  DM_Sans,
  Encode_Sans_Expanded,
  Encode_Sans_Semi_Condensed,
} from "next/font/google";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const encodeSansExpanded = Encode_Sans_Expanded({
  weight: ["400"],
  variable: "--font-encode-sans-expanded",
  subsets: ["latin"],
});

const encodeSansSemiCondensed = Encode_Sans_Semi_Condensed({
  weight: ["400", "600"],
  variable: "--font-encode-sans-semi-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${encodeSansExpanded.variable} ${encodeSansSemiCondensed.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
