import type { Metadata } from "next";
import {
  Encode_Sans_Expanded,
  Encode_Sans_Semi_Condensed,
} from "next/font/google";
import "./globals.css";

const encodeSansExpanded = Encode_Sans_Expanded({
  weight: ["400"],
  variable: "--font-encode-sans-expanded",
  subsets: ["latin"],
});

const encodeSansSemiCondensed = Encode_Sans_Semi_Condensed({
  weight: ["400"],
  variable: "--font-encode-sans-semi-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${encodeSansExpanded.variable} ${encodeSansSemiCondensed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
